"""
URLs da API para o app service_control
"""

from django.urls import path

from .api_views import (
    EventAddParticipantsAPIView,
    EventCreateAPIView,
    EventDetailAPIView,
    EventLinkServiceOrderAPIView,
    EventListWithStatusAPIView,
    EventOpenListAPIView,
    EventUpdateAPIView,
    RefusalReasonsListAPIView,
    ServiceOrderAttendantMetricsAPIView,
    ServiceOrderClientAPIView,
    ServiceOrderCreateAPIView,
    ServiceOrderDashboardAPIView,
    ServiceOrderDetailAPIView,
    ServiceOrderListAPIView,
    ServiceOrderListByClientAPIView,
    ServiceOrderListByPhaseAPIView,
    ServiceOrderListByPhaseV2APIView,
    ServiceOrderFinanceSummaryAPIView,
    ServiceOrderMarkPaidAPIView,
    ServiceOrderMarkReadyAPIView,
    ServiceOrderMarkRetrievedAPIView,
    ServiceOrderPreTriageAPIView,
    ServiceOrderRefuseAPIView,
    ServiceOrderReturnToPendingAPIView,
    ServiceOrderUpdateAPIView,
    VirtualServiceOrderCreateAPIView,
    VirtualServiceOrderDeleteAPIView,
)

urlpatterns = [
    # Eventos
    path(
        "events/create/",
        EventCreateAPIView.as_view(),
        name="api_event_create",
    ),
    path(
        "events/<int:event_id>/update/",
        EventUpdateAPIView.as_view(),
        name="api_event_update",
    ),
    path(
        "events/<int:event_id>/add-participants/",
        EventAddParticipantsAPIView.as_view(),
        name="api_event_add_participants",
    ),
    path(
        "events/open/",
        EventOpenListAPIView.as_view(),
        name="api_event_open_list",
    ),
    path(
        "events/link-service-order/",
        EventLinkServiceOrderAPIView.as_view(),
        name="api_event_link_service_order",
    ),
    path(
        "events/list-with-status/",
        EventListWithStatusAPIView.as_view(),
        name="api_event_list_with_status",
    ),
    path(
        "events/<int:event_id>/detail/",
        EventDetailAPIView.as_view(),
        name="api_event_detail",
    ),
    # Dashboard e métricas
    path(
        "service-orders/dashboard/",
        ServiceOrderDashboardAPIView.as_view(),
        name="api_service_order_dashboard",
    ),
    path(
        "service-orders/attendant-metrics/",
        ServiceOrderAttendantMetricsAPIView.as_view(),
        name="api_service_order_attendant_metrics",
    ),
    # Ordens de serviço
    path(
        "service-orders/",
        ServiceOrderListAPIView.as_view(),
        name="api_service_order_list",
    ),
    path(
        "service-orders/create/",
        ServiceOrderCreateAPIView.as_view(),
        name="api_service_order_create",
    ),
    path(
        "service-orders/virtual/",
        VirtualServiceOrderCreateAPIView.as_view(),
        name="api_virtual_service_order_create",
    ),
    path(
        "service-orders/virtual/<int:order_id>/",
        VirtualServiceOrderDeleteAPIView.as_view(),
        name="api_virtual_service_order_delete",
    ),
    path(
        "service-orders/<int:order_id>/",
        ServiceOrderDetailAPIView.as_view(),
        name="api_service_order_detail",
    ),
    path(
        "service-orders/<int:order_id>/update/",
        ServiceOrderUpdateAPIView.as_view(),
        name="api_service_order_update",
    ),
    path(
        "service-orders/<int:order_id>/mark-paid/",
        ServiceOrderMarkPaidAPIView.as_view(),
        name="api_service_order_mark_paid",
    ),
    path(
        "service-orders/<int:order_id>/refuse/",
        ServiceOrderRefuseAPIView.as_view(),
        name="api_service_order_refuse",
    ),
    path(
        "service-orders/refusal-reasons/",
        RefusalReasonsListAPIView.as_view(),
        name="api_refusal_reasons_list",
    ),
    path(
        "service-orders/<int:order_id>/mark-ready/",
        ServiceOrderMarkReadyAPIView.as_view(),
        name="api_service_order_mark_ready",
    ),
    path(
        "service-orders/<int:order_id>/mark-retrieved/",
        ServiceOrderMarkRetrievedAPIView.as_view(),
        name="api_service_order_mark_retrieved",
    ),
    path(
        "service-orders/<int:order_id>/return-to-pending/",
        ServiceOrderReturnToPendingAPIView.as_view(),
        name="api_service_order_return_to_pending",
    ),
    path(
        "service-orders/<int:order_id>/client/",
        ServiceOrderClientAPIView.as_view(),
        name="api_service_order_client",
    ),
    # Listagem por fase
    path(
        "service-orders/phase/<str:phase_name>/",
        ServiceOrderListByPhaseAPIView.as_view(),
        name="api_service_order_by_phase",
    ),
    path(
        "service-orders/v2/phase/<str:phase_name>/",
        ServiceOrderListByPhaseV2APIView.as_view(),
        name="api_service_order_by_phase_v2",
    ),
    # Listagem por cliente
    path(
        "service-orders/renter/<int:renter_id>/",
        ServiceOrderListByClientAPIView.as_view(),
        name="api_service_order_by_client",
    ),
    path(
        "service-orders/pre-triage/",
        ServiceOrderPreTriageAPIView.as_view(),
        name="api_service_order_pre_triage",
    ),
    # Finance tab
    path(
        "service-orders/finance/",
        ServiceOrderFinanceSummaryAPIView.as_view(),
        name="api_service_order_finance_summary",
    ),
]
