[pytest]
DJANGO_SETTINGS_MODULE = roupadegala.settings_test
python_files = tests.py test_*.py *_tests.py
python_classes = Test*
python_functions = test_*
testpaths = tests accounts service_control products
addopts = --tb=short -p no:warnings

log_cli = true
log_cli_level = INFO
