# Generated by Django 4.2.11 on 2026-02-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_control", "0030_alter_renter_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorder",
            name="client_name",
            field=models.CharField(
                blank=True,
                help_text="Nome do cliente (para OS virtual sem cliente cadastrado)",
                max_length=255,
                null=True,
            ),
        ),
    ]
