# Generated by Django 4.2.11 on 2026-03-24 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_add_is_infant_to_person"),
        ("service_control", "0031_add_client_name_to_serviceorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorder",
            name="data_resgate",
            field=models.DateField(
                blank=True,
                help_text="Data em que a OS foi resgatada (retornada de RECUSADA)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="is_partnership",
            field=models.BooleanField(
                default=False, help_text="OS de parceria/voucher (permite valor zero)"
            ),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="partnership_authorized_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Administrador que autorizou a parceria",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authorized_partnerships",
                to="accounts.person",
            ),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="partnership_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PARCERIA", "Parceria"),
                    ("VOUCHER", "Voucher"),
                    ("LINK", "Link"),
                ],
                help_text="Tipo de parceria",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="attendant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendant_service_orders",
                to="accounts.person",
            ),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="employee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee_service_orders",
                to="accounts.person",
            ),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="renter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_orders",
                to="accounts.person",
            ),
        ),
    ]
