# Generated by Django 4.2.11 on 2026-02-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_make_contact_address_fields_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="is_infant",
            field=models.BooleanField(default=False),
        ),
    ]
